// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApi.Database;

#nullable disable

namespace WeatherApi.Database.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20250327153416_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("WeatherApi.Database.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Feels_like")
                        .HasColumnType("REAL");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pressure")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temp")
                        .HasColumnType("REAL");

                    b.Property<double>("Temp_max")
                        .HasColumnType("REAL");

                    b.Property<double>("Temp_min")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WeatherDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feels_like = 15.0,
                            Humidity = 70,
                            Name = "Wrocław",
                            Pressure = 1013,
                            Temp = 15.5,
                            Temp_max = 18.0,
                            Temp_min = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Feels_like = 12.0,
                            Humidity = 75,
                            Name = "Warszawa",
                            Pressure = 1015,
                            Temp = 12.5,
                            Temp_max = 15.0,
                            Temp_min = 8.0
                        },
                        new
                        {
                            Id = 3,
                            Feels_like = 14.0,
                            Humidity = 72,
                            Name = "Kraków",
                            Pressure = 1012,
                            Temp = 14.5,
                            Temp_max = 17.0,
                            Temp_min = 9.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
